### ISSUE TITLE
handcuffs values

### ISSUE THREAD

**Issue by GeckoInverse** [MartinBlackburn/ARK-skill-tree#1]
Under tools->other Tools -> Handcuffs
The values for handcuffs are incorrect.
The correct values according to http://ark.gamepedia.com/Handcuffs are as follows:
Required Level 25
Engram points 16

Awesome job on this tool, its very organized and useful =)

**Comment by MartinBlackburn** [comment]
Thanks for pointing that out GeckoInverse, they have been updated
